# Generated by Django 4.0.3 on 2022-03-13 14:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Helper')], verbose_name='Account type')),
                ('account_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Helper',
                'verbose_name_plural': 'Helpers',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPickUpPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='City')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization Pick Up point',
                'verbose_name_plural': 'Organization Pick Up points',
                'unique_together': {('city', 'address')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Organization')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Organization Route',
                'verbose_name_plural': 'Organization Routes',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start time')),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Total seats')),
                ('vehicle', models.IntegerField(blank=True, choices=[(1, 'Car'), (2, 'Bus')], null=True, verbose_name='Vehicle type')),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='Vehicle registration number')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.helper', verbose_name='Helper')),
                ('organization_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationroute', verbose_name='Organization route')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
        migrations.CreateModel(
            name='TransferRouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Departure time')),
                ('pick_up_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizationpickuppoint', verbose_name='Pick up point')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.transfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Transfer Route Details',
                'verbose_name_plural': 'Transfer Route Details',
            },
        ),
        migrations.AddField(
            model_name='helper',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization', verbose_name='Organization'),
        ),
    ]
