# Generated by Django 4.0.3 on 2022-03-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
