# Generated by Django 4.0.3 on 2022-03-15 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='translators',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Translators'),
        ),
        migrations.CreateModel(
            name='OrganizationRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=63, unique=True, verbose_name='Headline')),
                ('rules', models.TextField(verbose_name='Rules')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization Rules',
                'verbose_name_plural': 'Organizations Rules',
            },
        ),
        migrations.AddField(
            model_name='transfer',
            name='rules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organizationrules', verbose_name='Rules'),
        ),
    ]
