# Generated by Django 4.0.3 on 2022-03-14 00:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('organization', '0002_helper_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='total_seats',
        ),
        migrations.RemoveField(
            model_name='transferroutedetails',
            name='pick_up_point',
        ),
        migrations.AddField(
            model_name='transfer',
            name='blanket',
            field=models.BooleanField(default=False, verbose_name='Blanket'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Additional remarks'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='drinks',
            field=models.BooleanField(default=False, verbose_name='Drinks'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='driver_seats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Driver seats'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='food',
            field=models.BooleanField(default=False, verbose_name='Food '),
        ),
        migrations.AddField(
            model_name='transfer',
            name='healthcare',
            field=models.BooleanField(default=False, verbose_name='Healthcare personnel'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='helper_seats',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Helper seats'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='refugee_seats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Refugee seats'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='secondary_helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_helper', to='organization.helper', verbose_name='Secondary Helper'),
        ),
        migrations.AddField(
            model_name='transferroutedetails',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='transferroutedetails',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_transfer_city', to='locations.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_helper', to='organization.helper', verbose_name='Helper'),
        ),
    ]
