# Generated by Django 4.0.3 on 2022-03-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_transfer_translators_organizationrules_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationRules',
            new_name='OrganizationTransferRules',
        ),
        migrations.AlterModelOptions(
            name='organizationtransferrules',
            options={'verbose_name': 'Organization Transfer Rules', 'verbose_name_plural': 'Organizations Transfer Rules'},
        ),
    ]
