# Generated by Django 4.0.3 on 2022-03-15 22:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_rename_organizationrules_organizationtransferrules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtransferrules',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 15, 22, 38, 39, 716432, tzinfo=utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationtransferrules',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
