# Generated by Django 4.0.3 on 2022-03-10 23:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refugee',
                'verbose_name_plural': 'Refugees',
            },
        ),
        migrations.CreateModel(
            name='TransferServiceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Seats')),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_city', to='locations.city', verbose_name='City')),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugee.refugee', verbose_name='Refugee')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_city', to='locations.city', verbose_name='City')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.transfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Transfer Reservation',
                'verbose_name_plural': 'Transfer Reservations',
                'unique_together': {('transfer', 'refugee')},
            },
        ),
    ]
