# Generated by Django 4.0.3 on 2022-03-10 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_delete_route_delete_routecities'),
        ('volunteer', '0005_alter_transferservice_volunteer'),
        ('refugee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferServiceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_city', to='locations.city', verbose_name='City')),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugee.refugee', verbose_name='Refugee')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_city', to='locations.city', verbose_name='City')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.transferservice', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Transfer Service Reservation',
                'verbose_name_plural': 'Transfer Service Reservations',
                'unique_together': {('transfer', 'refugee')},
            },
        ),
    ]
