# Generated by Django 4.0.3 on 2022-03-12 00:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_alter_transferroutedetails_unique_together'),
        ('refugee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Seats')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_city', to='volunteer.transferroutedetails', verbose_name='From city')),
                ('refugee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refugee.refugee', verbose_name='Refugee')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_city', to='volunteer.transferroutedetails', verbose_name='To city')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.transfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Transfer Reservation',
                'verbose_name_plural': 'Transfer Reservations',
                'unique_together': {('transfer', 'refugee')},
            },
        ),
        migrations.DeleteModel(
            name='TransferServiceReservation',
        ),
    ]
