# Generated by Django 4.0.3 on 2022-03-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='vehicle',
            field=models.IntegerField(blank=True, choices=[(1, 'Car'), (2, 'Bus')], null=True, verbose_name='Vehicle type'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Vehicle registration number'),
        ),
    ]
