# Generated by Django 4.0.3 on 2022-03-09 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import volunteer.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_route'),
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('pick_up_time', models.DateTimeField(verbose_name='Pick up time')),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Total seats')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.route', verbose_name='Route')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.volunteer', verbose_name=volunteer.models.Volunteer)),
            ],
            options={
                'verbose_name': 'Transfer Service',
                'verbose_name_plural': 'Transfer Service',
            },
        ),
    ]
