# Generated by Django 4.0.3 on 2022-03-09 19:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_routecities_unique_together_and_more'),
        ('volunteer', '0002_transferservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferservice',
            name='route',
        ),
        migrations.CreateModel(
            name='TransferRouteCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Order')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='City')),
                ('transfer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.transferservice', verbose_name='Transfer ID')),
            ],
            options={
                'verbose_name': 'Transfer Route Cities',
                'verbose_name_plural': 'Transfer Route Cities',
                'unique_together': {('transfer_id', 'city')},
            },
        ),
    ]
