# Generated by Django 4.0.3 on 2022-03-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('volunteer', '0002_transfer_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': 'Transfer', 'verbose_name_plural': 'Transfers'},
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='pick_up_time',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='route',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='transfer',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.CreateModel(
            name='VolunteerRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.route', verbose_name='Route')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer', verbose_name='Volunteer')),
            ],
            options={
                'verbose_name': 'Volunteer Route',
                'verbose_name_plural': 'Volunteers Routes',
            },
        ),
        migrations.CreateModel(
            name='TransferRouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('departure_time', models.DateTimeField(verbose_name='Departure time')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city', verbose_name='City')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.transfer', verbose_name='Transfer')),
            ],
            options={
                'verbose_name': 'Transfer Route Details',
                'verbose_name_plural': 'Transfer Route Details',
            },
        ),
        migrations.AddField(
            model_name='transfer',
            name='volunteer_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.volunteerroute', verbose_name='Volunteer-Route'),
        ),
    ]
