# Generated by Django 4.0.3 on 2022-03-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_remove_transferservice_route_transferroutecities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferroutecities',
            old_name='transfer_id',
            new_name='transfer',
        ),
    ]
