# Generated by Django 4.0.3 on 2022-03-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('volunteer', '0003_alter_transfer_options_remove_transfer_pick_up_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transferroutedetails',
            unique_together={('transfer', 'city')},
        ),
    ]
