# Generated by Django 4.0.3 on 2022-03-10 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_rename_transfer_id_transferroutecities_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferservice',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.volunteer', verbose_name='Volunteer'),
        ),
    ]
