# Generated by Django 4.0.3 on 2022-03-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_route_unique_together_remove_route_city_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routecities',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='routecities',
            name='city',
        ),
        migrations.RemoveField(
            model_name='routecities',
            name='route_id',
        ),
    ]
