# Generated by Django 4.0.3 on 2022-03-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_routecities_unique_together_and_more'),
        ('volunteer', '0003_remove_transferservice_route_transferroutecities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='RouteCities',
        ),
    ]
